services:
  mongo-joueur:
    image: mongo
    container_name: mongo-joueur
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=passadmin
    volumes:
      - mongo-joueur:/persist/joueur
    expose:
      - 27018
    ports:
      - "27018:27017"
    restart: on-failure
    networks:
      - gatcha-lan

  api-joueur:
    build: ../
    container_name: api-joueur
    ports:
      - "8081:8080"
    networks:
      - gatcha-lan

volumes:
  mongo-joueur:


networks:
  gatcha-lan:
    external: true
