services:
  mongo-auth:
    image: mongo
    container_name: mongo-joueur
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=passadmin
    volumes:
      - mongo-joueur:/persist/joueur
    expose:
      - 27017
    ports:
      - "27018:27017"
    restart: on-failure

  api-joueur:
    build: ../
    container_name: api-joueur
    ports:
      - "8081:8080"


volumes:
  mongo-joueur:
